### ISSUE TITLE
from Toolbox.Preprocessing import Processor error 

### ISSUE THREAD

**Issue by ucalyptus** [AngryCai/BandSelection#5]
Please look into it as to which Python module this is and what is its significance

**Comment by ucalyptus** [comment]
I am getting the error, no module named Toolbox.

**Comment by AngryCai** [comment]
Thank you point this out. Toolbox is replaceable. Actually, we use it to partition training/test set and calculate some metrics, etc.

**Comment by ucalyptus** [comment]
Yes I found the toolbox under Research repository. Thanks a lot.
